// <auto-generated />
namespace Springboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SkillIntegration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SkillIntegration));
        
        string IMigrationMetadata.Id
        {
            get { return "201603131912496_SkillIntegration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
